DROP TABLE SCORE;	
CREATE TABLE SCORE(
	NAME VARCHAR2(20) PRIMARY KEY,
	KOR NUMBER NOT NULL,
	ENG NUMBER NOT NULL,
	MATH NUMBER NOT NULL,
	SUM NUMBER,
	AVG NUMBER,
	GRADE CHAR(2) CHECK(GRADE IN ('A','B','C','D','F'))
);
INSERT INTO SCORE VALUES('LEE',100,100,100,300,100.0,'A');
SELECT * FROM SCORE;